# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsClickUsers',
            fields=[
                ('ads_id', models.AutoField(primary_key=True, serialize=False)),
                ('ads_company_id', models.IntegerField()),
                ('user_profile_id', models.IntegerField()),
                ('ip_address', models.CharField(max_length=50)),
                ('clicks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_click_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsCompany',
            fields=[
                ('ads_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('ads_company_name', models.CharField(max_length=255)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdsEvent',
            fields=[
                ('ads_id', models.AutoField(primary_key=True, serialize=False)),
                ('ads_company_id', models.IntegerField()),
                ('ads_name', models.CharField(max_length=255)),
                ('ads_status', models.CharField(blank=True, max_length=1, null=True)),
                ('ads_location_name', models.CharField(max_length=255)),
                ('ads_location_latitude', models.FloatField()),
                ('ads_location_longitude', models.FloatField()),
                ('ads_location_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_location_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ads_start_time', models.TimeField(blank=True, null=True)),
                ('ads_end_time', models.TimeField(blank=True, null=True)),
                ('ads_exposure_time', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ads_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('parking_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_lot_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('location_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'parking_lot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLotFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_lot_id', models.IntegerField()),
                ('user_profile_id', models.IntegerField()),
                ('feedback', models.TextField()),
                ('rating', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'parking_lot_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLotPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot_id', models.IntegerField()),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking_lot_price',
                'managed': False,
            },
        ),
    ]
